[package]
name = "explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
binc = { path = "../binc" }
eframe = "0.31.0"
env_logger = "0.11.6"
rfd = "0.15.2"
xml = "0.8.20"

[[bin]]
name = "binc-explorer"
path = "src/explorer.rs"
