[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
binc = { path = "../binc" }
clap = { version = "4.5.28", features = ["derive"] }
uuid = { version = "1.13.1", features = ["v4"] }