[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
binc = { path = "../binc" }
eframe = "0.30.0"
env_logger = "0.11.6"
rfd = "0.15.2"
uuid = { version = "1.12.1", features = ["v4"] }