[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
binc = { path = "../binc" }
gui = { path = "../gui" }
eframe = "0.30.0"
env_logger = "0.11.6"
uuid = { version = "1.13.1", features = ["v4"] }